version: 1

filters:
  telegram_info_filter:
    (): utils.logging.log_filters.TelegramInfoFilter
  
  telegram_chart_filter:
    (): utils.logging.log_filters.TelegramChartFilter
  
  stdout_info_filter:
    (): utils.logging.log_filters.StdoutInfoFilter


formatters:
  stdout:
    format: '{message}'
    style: '{'
  
  telegram: 
    format: '{message}'
    style: '{' 

handlers: 
  stdout:
    class: logging.StreamHandler
    level: INFO
    stream: ext://sys.stdout
    filters: [stdout_info_filter]
    formatter: stdout

  telegram_info:
    class: utils.logging.log_handlers.TelegramInfoHandler
    level: INFO
    filters: [telegram_info_filter]

  telegram_chart:
    class: utils.logging.log_handlers.TelegramChartHandler
    level: INFO
    filters: [telegram_chart_filter]
  
loggers:
  seg:
    level: INFO
    handlers: [stdout, telegram_info, telegram_chart]
