mode: train
task: clr
nn_model: pnet_256
device: cuda
crop: 256
epoch: 1000
transform_data_every_n_epoch: 10
make_checkpoint_every_n_epoch: 5

telegram_send_logs: True
checkpoint: model\checkpoints\pnet_256_adam_reducelronplateau_crop256\80_epoch.pt
checkpoints_path: model/checkpoints

datasets:
  normalize:
    mean: [0.4784, 0.4460, 0.4028]
    std: [0.2293, 0.2237, 0.2249]

  train:
    load_to_ram: false
    imgs_path: "data/clr_damage_data/train/images/"
    masks_path: "data/clr_damage_data/train/masks/"

    transforms:
      colorjitter:
        p: .05
        brightness: [.1, .2, .3]
        contrast: [.1, .2, .3]
        saturation: [.1, .2, .3]
        hue: [.1, .2]

      randomequalize:
        p: .1

      grayscale:
        p: .25
        num_output_channels: 3

      randomhorizontalflip:
        p: .5

      randomverticalflip:
        p: .5

  test:
    load_to_ram: false
    imgs_path: "data/clr_damage_data/test/images/"
    masks_path: "data/clr_damage_data/test/masks/"

dataloaders:
  train:
    batch_size: 16
    shuffle: true
    num_workers: 8
    pin_memory: true
    drop_last: false

  test:
    batch_size: 16
    num_workers: 8
    shuffle: false
    drop_last: false

nns:
  metrics:
    [ssim, mse, psnr]

  criterion:
    inpainting:
      lambdas:
        valid: 1
        hole: 6.0 
        tv: 0.05
        prc: 0.03
        style: 3


  models:
    pnet_256:
      activation_function_1: relu
      activation_function_2: leakyrelu

      optimizer:
        name: adam
        lr: 1e-3
      
      # scheduler:
      #   scheme: exponentiallr
      #   gamma: 0.95

      scheduler:
        scheme: ReduceLROnPlateau
        factor: .1
        patience: 5
        cooldown: 5
        threshold: 1e-6
        eps: 1e-12
      
