name: uppicres
logs_path: logs/
device: cuda
patches_to_device: 4
crop: 256

seg:
  normalize:
    mean: [0.4941, 0.4605, 0.4085]
    std: [0.1446, 0.1396, 0.1307]
  pos_label_threshold: 0.75

nns: # DO NOT CHANGE!
  UnetWide256:
    in_channels: 3
    out_channels: 1
    activation_function: "relu"

    path: model\pretrained\UnetWide256.pt
  
